CREATE DATABASE classwork23feb;
USE classwork23feb;

CREATE TABLE Dept(
DEPTNO int not null auto_increment primary key,
DNAME VARCHAR(100),
LOC VARCHAR(20)
);

ALTER TABLE Dept ADD PINCODE INT NOT NULL;

ALTER TABLE Dept RENAME TO Department;

ALTER table Department
RENAME COLUMN DNAME TO DEPT_NAME;

ALTER TABLE Department
MODIFY COLUMN LOC CHAR(10);

SELECT * FROM DEPARTMENT;

DROP TABLE DEPARTMENT;




